### ISSUE TITLE
oauth

### ISSUE THREAD

**Issue by xverizex** [Sn0wy-0wl/TwitchHive#1]
https://github.com/Sn0wy-0wl/TwitchHive/blob/820c8ecc9dfe934a2c708c906a28af6636e2a2af/HiveMind.py#L12

привет. у тебя тут oauth авторизация для бота написана. её могут использовать для написания сообщений от твоего имени.

**Comment by Sn0wy-0wl** [comment]
@xverizex пхах, как я мог токен оставить, спасибо))
